version: '3.8'

services:
  blog:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        # 使用宿主机当前用户的 UID/GID（Linux 系统）
        # macOS/Windows 可以使用默认值 1001
        USER_ID: ${USER_ID:-1001}
        GROUP_ID: ${GROUP_ID:-1001}
      platforms:
        - linux/amd64
        - linux/arm64
    image: lynn/tiny-blog:v1
    ports:
      - "${BLOG_PORT:-3131}:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - REVALIDATE_SECRET=${REVALIDATE_SECRET}
      - USER_ID=${USER_ID:-1001}
      - GROUP_ID=${GROUP_ID:-1001}
      # 站点配置环境变量
      - SITE_URL=${SITE_URL}
      - GITHUB_URL=${GITHUB_URL:-}
      - EMAIL=${EMAIL:-}
      - TWITTER_URL=${TWITTER_URL:-}
    volumes:
      # 使用单一数据目录，在其下创建 content, config 子目录
      # images 存储在 content/images 中，通过 /api/images API 访问
      - ${DATA_PATH:-./blog-data}/content:/app/content
      - ${DATA_PATH:-./blog-data}/config:/app/config
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - blog-network
    # 资源限制配置
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    # 日志配置
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  blog-network:
    driver: bridge